# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Pull request CI checks

defaults:
  run:
    working-directory: "frontend"

on:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**" # NOTE: "frontend" alone won't trigger the checks, because it just matches the folder itself
      - "!**/*.{txt,md}"

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ">=24.3.0" # latest as of July 2025; see https://nodejs.org/en/about/previous-releases for schedule
      - name: install
        run: npm install

      - name: check with eslint
        run: npx eslint "{src,test}/**/*" --max-warnings=0

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ">=24.3.0"
      - name: install
        run: npm install

      - name: run testcases
        run: npm test
